### ISSUE TITLE
Felipe Borges

### ISSUE THREAD

**Issue by Bumbleblo** [FGA-GCES/Trabalho-Individual-2021-2#32]
Repositório: https://github.com/Bumbleblo/Trabalho-Individual-GCES-2021-2
Não trabalhei no lint, test e build, porém tem deploy no dockerhub: https://hub.docker.com/repository/docker/bumbleblo/gces-trabalho

**Comment by renatocoral** [comment]
| Item                                                                                                                                          | Nota | Observações               |
| --------------------------------------------------------------------------------------------------------------------------------------------- | ---- | ------------------------- |
| 1\. Containerização                                                                                                                           |      |                           |
| Banco de Dados                                                                                                                                | 1,0  | Implementado              |
| Aplicação + Banco                                                                                                                             | 2,0  | Implementado              |
| Aplicação + Banco + Nginx                                                                                                                     | 2,0  | Implementado              |
| 2\. Integração contínua                                                                                                                       |      |                           |
| Build: Construção completa do ambiente                                                                                                        | 0,0  | Não implementado          |
| Testes: Os testes automatizados da aplicação devem ser executados                                                                             | 0,0  | Não implementado          |
| Coleta de métricas: Deverá ser realizada a integração com algum serviço externo de coleta de métricas de qualidade; Ex: lint)                 | 0,0  | Não implementado          |
| 5\. Deploy contínuo                                                                                                                           |      |                           |
| Configuração da pipeline de modo a publicar a aplicação automaticamente, sempre que um novo trecho de código seja integrado à branch default. | 2,0  | Implementado (Docker Hub) |
| Total                                                                                                                                         | 7,0  |

**Comment by Bumbleblo** [comment]
Renato, no PDF fornecido anteriormente a nota estava com o total de 4. Poderia conferir por favor ? Acho que não afeta a minha menção mas pode ser que tenha confundido com alguém.
